const jobs = [
  {
    id: 1,
    company: "Razorpay",
    role: "SDE Intern",
    status: "Applied",
    location: "Bangalore",
    appliedDate: "2026-07-01",
    recruiter: "Priya Sharma",
    salary: "₹12 LPA",
    jobType: "Internship",
    notes: "Applied through company careers page.",
    link: "https://razorpay.com/careers"
  },
  {
    id: 2,
    company: "Zomato",
    role: "Frontend Intern",
    status: "Applied",
    location: "Gurgaon",
    appliedDate: "2026-07-03",
    recruiter: "Rahul Gupta",
    salary: "₹10 LPA",
    jobType: "Internship",
    notes: "Referral from LinkedIn.",
    link: "https://careers.zomato.com"
  },
  {
    id: 3,
    company: "Microsoft",
    role: "Software Engineer Intern",
    status: "Applied",
    location: "Hyderabad",
    appliedDate: "2026-07-05",
    recruiter: "Anjali Singh",
    salary: "₹18 LPA",
    jobType: "Internship",
    notes: "Applied via Microsoft Careers.",
    link: "https://careers.microsoft.com"
  },
  {
    id: 4,
    company: "Swiggy",
    role: "Backend Intern",
    status: "OA / Screening",
    location: "Bangalore",
    appliedDate: "2026-06-25",
    recruiter: "Nikhil Verma",
    salary: "₹11 LPA",
    jobType: "Internship",
    oaDate: "2026-07-10",
    notes: "OA completed.",
    link: "https://careers.swiggy.com"
  },
  {
    id: 5,
    company: "Groww",
    role: "SDE Intern",
    status: "OA / Screening",
    location: "Bangalore",
    appliedDate: "2026-06-29",
    recruiter: "Sneha Kapoor",
    salary: "₹14 LPA",
    jobType: "Internship",
    oaDate: "2026-07-12",
    notes: "Waiting for OA results.",
    link: "https://groww.in/careers"
  },
  {
    id: 6,
    company: "PhonePe",
    role: "Backend Engineer",
    status: "OA / Screening",
    location: "Bangalore",
    appliedDate: "2026-07-02",
    recruiter: "Arjun Rao",
    salary: "₹22 LPA",
    jobType: "Full Time",
    oaDate: "2026-07-14",
    notes: "Technical assessment pending.",
    link: "https://www.phonepe.com/careers"
  },
  {
    id: 7,
    company: "Dunzo",
    role: "Full Stack Intern",
    status: "Interview",
    location: "Remote",
    appliedDate: "2026-06-20",
    recruiter: "Amit Jain",
    salary: "₹9 LPA",
    jobType: "Internship",
    interviewDate: "2026-07-18",
    interviewTime: "4:00 PM",
    interviewRound: "Technical Round 1",
    notes: "Prepare DSA and React.",
    link: "https://dunzo.com/careers"
  },
  {
    id: 8,
    company: "CRED",
    role: "Frontend Engineer",
    status: "Interview",
    location: "Bangalore",
    appliedDate: "2026-06-18",
    recruiter: "Ritika Malhotra",
    salary: "₹20 LPA",
    jobType: "Full Time",
    interviewDate: "2026-07-20",
    interviewTime: "11:00 AM",
    interviewRound: "Hiring Manager",
    notes: "System Design discussion.",
    link: "https://careers.cred.club"
  },

  {
    id: 10,
    company: "Meesho",
    role: "SDE Intern",
    status: "Offer",
    location: "Bangalore",
    appliedDate: "2026-06-01",
    recruiter: "Karan Patel",
    salary: "₹15 LPA",
    jobType: "Internship",
    offerDate: "2026-07-08",
    joiningDate: "2027-01-05",
    notes: "Offer accepted.",
    link: "https://www.meesho.io/jobs"
  },
  {
    id: 11,
    company: "Amazon",
    role: "Software Development Engineer",
    status: "Offer",
    location: "Hyderabad",
    appliedDate: "2026-05-28",
    recruiter: "Sarah Williams",
    salary: "₹32 LPA",
    jobType: "Full Time",
    offerDate: "2026-07-06",
    joiningDate: "2027-02-01",
    notes: "Negotiating compensation.",
    link: "https://amazon.jobs"
  },
  {
    id: 12,
    company: "Adobe",
    role: "Frontend Engineer",
    status: "Rejected",
    location: "Noida",
    appliedDate: "2026-05-15",
    recruiter: "Rohit Mehta",
    salary: "₹24 LPA",
    jobType: "Full Time",
    rejectedDate: "2026-06-10",
    notes: "Rejected after final interview.",
    link: "https://careers.adobe.com"
  }
];

export default jobs;